Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/xenial64"
    web01.vm.hostname = "web01"
	web01.vm.network "private_network", ip: "192.168.33.11"
	web01.vm.synced_folder "../vprofile-code", "/vprofile-vm-data"
  end
  
### tomcat vm ###
   config.vm.define "app01" do |app01|
    app01.vm.box = "geerlingguy/centos7"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.33.12"
    app01.vm.synced_folder "../vprofile-code", "/vprofile-vm-data"
	app01.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	 end
	app01.vm.provision "shell", inline: <<-SHELL
     yum update -y
	 yum install epel-release -y
   SHELL
   end
   
### RabbitMQ vm  ####
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "geerlingguy/centos7"
	rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.33.16"
	rmq01.vm.synced_folder "../vprofile-code", "/vprofile-vm-data"
	rmq01.vm.provision "shell", inline: <<-SHELL
    yum update -y
	yum install epel-release -y
	 yum install socat -y
	 yum install erlang -y
	 yum install wget -y
    SHELL
  end
  
### Memcache vm  #### 
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "geerlingguy/centos7"
	mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.33.14"
	mc01.vm.synced_folder "../vprofile-code", "/vprofile-vm-data"
	mc01.vm.provision "shell", inline: <<-SHELL
     yum install epel-release -y
    SHELL
  end
  
### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
	db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.33.15"
	db01.vm.synced_folder "../vprofile-code", "/vprofile-vm-data"
	db01.vm.provision "shell", inline: <<-SHELL
	yum update -y
    yum install epel-release -y
    SHELL
  end
  
  
end
