def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "maven"
        jdk "OracleJDK11"
    }
    
    environment {
        cluster = "vprofile-pipeline-production"
        service = "vproapp-production-service"
    }

    stages {
       stage ('Deploy to Production ECS'){
        steps {
            withAWS(credentials: 'awscredentials', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                } 
        }
       }
    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#jenkinscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More 		info at: ${env.BUILD_URL}"
        }
    }
}
