def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any

    environment {
        cluster = "bonny-vproprod"
        service = "vproprodsvc"
    }

    stages {
        stage('Deploy to Prod ecs') {
          steps {
        withAWS(credentials: 'aws-cred-id', region: 'us-east-2') {
          sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
        }
      }
     }

    }
    
    post {
        always {
            echo 'Slack Notifications.'
            slackSend (
                channel: '#jenkinscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
            )

            mail (
                to: 'jofranco1203@gmail.com',
                subject: "Build ${env.JOB_NAME} - #${env.BUILD_NUMBER} ${currentBuild.currentResult}",
                body: "Build details: ${env.BUILD_URL}"
            )    
        }
    }
}