Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "kubemaster" do |kubemaster|
    kubemaster.vm.box = "ubuntu/focal64"
	kubemaster.vm.network "private_network", ip: "192.168.33.2"
	kubemaster.vm.provider "virtualbox" do |vb|
            vb.name = "kubemaster"
            vb.memory = 2048
            vb.cpus = 2
        end
	kubemaster.vm.hostname = "kubemaster"
	kubemaster.vm.provision "shell", path: "kubemaster-init.sh"
  end

  config.vm.define "kubenode1" do |kubenode1|
    kubenode1.vm.box = "ubuntu/focal64"
	kubenode1.vm.network "private_network", ip: "192.168.33.3"
        kubenode1.vm.provider "virtualbox" do |vb|
            vb.name = "kubenode1"
            vb.memory = 1028
            vb.cpus = 2
        end
        kubenode1.vm.hostname = "kubenode1"
	kubenode1.vm.provision "shell", path: "kubenode1-init.sh"
  end

  config.vm.define "kubenode2" do |kubenode2|
    kubenode2.vm.box = "ubuntu/focal64"
        kubenode2.vm.network "private_network", ip: "192.168.33.4"
        kubenode2.vm.provider "virtualbox" do |vb|
            vb.name = "kubenode2"
            vb.memory = 1028
            vb.cpus = 2
        end
        kubenode2.vm.hostname = "kubenode2"
	kubenode2.vm.provision "shell", path: "kubenode2-init.sh"
  end
end
