  version: 0.2
env: 
  parameter-store:
    CODEARTIFACT_AUTH_TOKEN: CODEARTIFACT_AUTH_TOKEN
    dbhost: RDS-Endpoint
    dbuser: RDSUSER
    dbpass: RDSPASS
    mchost: orange-memcached-url
    rmqhost: orange-rmq
    rmquser: orange-rmq-user
    rmqpass: orange-rmq-pass
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - cp ./settings.xml /root/.m2/settings.xml
  pre_build:
    commands:
      - sed -i "s/jdbc.password=admin123/jdbc.password=$dbpass/" src/main/resources/application.properties
      - sed -i "s/jdbc.username=admin/jdbc.username=$dbuser/" src/main/resources/application.properties
      - sed -i "s/db01:3306/$dbhost:3306/" src/main/resources/application.properties
      - sed -i "s/memcached.active.host=mc01/memcached.active.host=$mchost/" src/main/resources/application.properties
      - sed -i "s/rabbitmq.address=rmq01/rabbitmq.address=$rmqhost/" src/main/resources/application.properties
      - sed -i "s/rabbitmq.port=5672/rabbitmq.port=5671/" src/main/resources/application.properties
      - sed -i "s/rabbitmq.username=test/rabbitmq.username=$rmquser/" src/main/resources/application.properties
      - sed -i "s/rabbitmq.password=test/rabbitmq.password=$rmqpass/" src/main/resources/application.properties
      - apt-get update
      - apt-get install -y jq 
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven
  build:
    commands:
      - mvn clean install -DskipTests
artifacts:
  files:
     - target/**/*.war
  discard-paths: yes
  name: ROOT.war
